[directory]
style = "bold blue"

[git_metrics]
disabled = false

# [git_status]
# format = '([\[$all_status$ahead_behind\]]($style) )'
# conflicted = "ğŸ³"
# ahead = "ğŸğŸ’¨"
# behind = "ğŸ˜°"
# diverged = "ğŸ˜µ"
# ahead = "ğŸğŸ’¨ â‡¡${count}"
# diverged = "ğŸ˜µ â‡•â‡¡${ahead_count}â‡£${behind_count}"
# behind = "ğŸ˜° â‡£${count}"
# untracked = "ğŸ¤·"
# stashed = "ğŸ“¦"
# modified = "ğŸ“"
# staged = '[++\($count\)](green)'
# renamed = "ğŸ‘…"
# deleted = "ğŸ—‘"
# up_to_date = '[âœ”](bold green)'

# [localip]
# disabled = false
# ssh_only = false

[python]
python_binary = ["./venv/bin/python", "python3"]

[shell]
powershell_indicator = "pwsh"
zsh_indicator = ""
style = "cyan"
disabled = true

[status]
disabled = false
map_symbol = true
pipestatus = true

[sudo]
disabled = false
